version: "3.8"
services:
  wfly-db:
    container_name: "wfly-db"
    image: mysql:latest
    restart: unless-stopped
#    networks:
#      - wfly
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: asdf
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pw
  wfly-srv:
    image: wfly/customimage
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "9990:9990"
#    networks:
#      - wfly
    build:
      dockerfile: Dockerfile
#networks:
#  wfly:
#    driver: bridge